### PR TITLE
Added functionality for renaming a GitHub repo.

### PR DESCRIPTION
**Pull request by hakuch**
As a very small HackDay (13 February 2015) project.

Tested using the Lita Vagrant VM and my own Github account using an application authentication token.

@theckman

### CODE REVIEW

**Comment by theckman** [comment]
Running tests locally caused the linters to fail:

```
Running RuboCop...
Inspecting 17 files
.......C.........

Offenses:

lib/lita/handlers/github_repo.rb:77:121: C: Line is too long. [142/120]
          'gh repo rename PagerDuty/lita-github better-lita-github' => 'Rename the PagerDuty/lita-github repo to PagerDuty/better-lita-github'
                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^
lib/lita/handlers/github_repo.rb:335:43: C: Redundant curly braces around a hash parameter.
          octo.edit_repository(full_name, { :name => new_repo } )
                                          ^^^^^^^^^^^^^^^^^^^^^
lib/lita/handlers/github_repo.rb:335:45: C: Use the new Ruby 1.9 hash syntax.
          octo.edit_repository(full_name, { :name => new_repo } )
                                            ^^^^^^^^
lib/lita/handlers/github_repo.rb:335:64: C: Space inside parentheses detected.
          octo.edit_repository(full_name, { :name => new_repo } )
```

If you need any help/suggestions resolving these let me know.

**Comment by theckman** [comment]
To add, for some reason Travis isn't building your PR. Not sure why.

**Comment by hakuch** [comment]
All the tests are passing now.

**Comment by theckman** [comment]
Can you also work on getting tests added to this for the functionality you added?

**Comment by hakuch** [comment]
Pinging @theckman . :)

**Pull request merged**
